### ISSUE TITLE
[Feature-Request] Textures

### ISSUE THREAD

**Issue by servusdei2018** [glouw/littlewolf#11]
It would be great if littlewolf could map textures onto the walls, ceilings and floor.

**Comment by glouw** [comment]
@servusDei2018  It's unfortunately a little complicated and will only detract from littlewolf's intended simplicity.

Check out https://github.com/glouw/andvaranaut for textured walls. Andvaranaut is Littlewolf pushed to the extreme.

**Comment by servusdei2018** [comment]
Thankyou @glouw , that looks perfect!
