### ISSUE TITLE
Change the turning keys from "h l" to "left right"

### ISSUE THREAD

**Issue by FlyingChickens64** [glouw/littlewolf#12]
Just an ease of use suggestion. I found that using h and l is kind of uncomfortable. I think changing them to left and right would be a little better.

**Comment by glouw** [comment]
True, but as a vim user, its nice to be able to make changes and not leave the home row when testing the engine. Considering little wolf is more of a demo renderer as opposed to anything else, a separate fork with newer updates might be better.

**Comment by FlyingChickens64** [comment]
Ah ok. It isn't too hard to change the controls to left and right for myself anyway, considering the entire thing is in one file. Thanks for your help.
