### ISSUE TITLE
SDL2 vs SDL2-dev

### ISSUE THREAD

**Issue by margusanvelt** [glouw/littlewolf#5]
Hi, in the README it sais both SDL2 and SDL2dev should work. 

I had libsdl2-2.0-0 installed but it did not work so i installed sdl2-dev and it worked.

**Comment by glouw** [comment]
I believe the dev package on Mac is just called SDL2, while linux and friends has SDL2-dev for development and runtime and SDL2 for runtime.

Either or best to install both.

**Comment by AokiAhishatsu** [comment]
SDL2.dll for Windows works also.
