### ISSUE TITLE
Support for Visual Studio 2015

### ISSUE THREAD

**Issue by mottosso** [glouw/littlewolf#6]
Hi @glouw,

Is it possible to build littlewolf using Visual Studio 2015 or above?

**Comment by glouw** [comment]
Yes, main.c is the only C file you need to import to visual studio. It is fully compilable by all C++ compiler standards, so feel free to rename it to main.cpp.

SDL2 for visual studio can be found here:

https://www.libsdl.org/release/SDL2-devel-2.0.8-VC.zip

**Comment by mottosso** [comment]
Oh, yes you're right. That was easy. Thanks for a great and inspirational project! :)

**Comment by glouw** [comment]
np. All the best.
