### ISSUE TITLE
Interested in an SDL 1.2 version?

### ISSUE THREAD

**Issue by classilla** [glouw/littlewolf#7]
Since this engine is pretty uncomplicated I ported it to Power Mac under SDL 1.2 (now you can compile `-DSDL1` to get an SDL 1.2 version, assuming you have `SDLMain.m`). I can do this as a PR if you're interested; if not, I'll do this in a repository of my own.

**Comment by glouw** [comment]
nice work, though I think SDL2 is best

**Comment by classilla** [comment]
No worries, then. I'll maintain those changes separately. The other change I made was not to render on every frame if the hero hasn't changed position or view, which now can run at a ripping pace even on a 15-year-old G4.

Anyway, it's a fun program, so thanks for coming up with it.

**Comment by glouw** [comment]
Thankyou. Glad you enjoyed
